export enum itemsTypes {
    SEARCH_ITEMS = 'items/SEARCH_ITEMS',
    SEARCH_ITEMS_SUCCESS = 'items/SEARCH_ITEMS_SUCCESS',
    SEARCH_ITEMS_FAILED = 'items/SEARCH_ITEMS_FAILED',
    GET_ITEM_DETAIL = 'items/GET_ITEM_DETAIL',
    GET_ITEM_DETAIL_SUCCESS = 'items/GET_ITEM_DETAIL_SUCCESS',
    GET_ITEM_DETAIL_FAILED = 'items/GET_ITEM_DETAIL_FAILED',
  }